name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: slack-utils-template
          changelog-types: '[{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"docs","section":"Documentation"},{"type":"chore","section":"Miscellaneous"}]'
